In [1]:
import numpy as np
import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt
from datetime import date
import statsmodels.api as sm

In [2]:
# Assets for the portfolio

tickers = [
    "SPY",   # S&P 500 ETF
    "AAPL",  # Apple
    "NVDA",  # Nvidia
    "MSFT",  # Microsoft
    "JPM",   # JPMorgan Chase
    "BAC",   # Bank of America
    "SHEL",  # Shell
    "XOM",   # Exxon Mobil
    "GLD",   # SPDR Gold Shares
    "BZ=F",  # Brent crude oil futures
    "NG=F"   # Natural gas (Henry Hub) futures
]


# Time period
START_DATE = "2010-01-01"
END_DATE = date.today().strftime("%Y-%m-%d")

In [3]:
# Getting data from Yahoo Finance

data = yf.download(
    tickers,
    start=START_DATE,
    end=END_DATE,
    interval="1d",
    auto_adjust=True,
    progress=False
)

In [4]:
data

Price            Close                                                 \
Ticker            AAPL        BAC        BZ=F         GLD         JPM
Date
2010-01-04    6.400960  11.977122   80.120003  109.800003   28.152376
2010-01-05    6.412027  12.366440   80.589996  109.699997   28.697685
2010-01-06    6.310033  12.511472   81.889999  111.510002   28.855364
2010-01-07    6.298368  12.923692   81.510002  110.820000   29.426964
2010-01-08    6.340244  12.809187   81.370003  111.370003   29.354692
...                ...        ...         ...         ...         ...
2026-09-28  338.399994  55.470001  105.279999  377.910004  336.589996
2026-09-29  329.399994  54.959999  102.589996  382.890015  334.980011
2026-09-30  333.019989  54.430000  103.529999  380.839996  330.829987
2026-10-01  330.320007  53.730000  102.309998  382.760010  333.179993
2026-10-02  333.690002  53.750000  102.250000  380.140015  332.380005

Price                                                             ...  \
Ticker            MSFT   NG=F        NVDA       SHEL         SPY  ...
Date                                                              ...
2010-01-04   22.984241  5.884    0.422817  26.799503   84.369003  ...
2010-01-05   22.991663  5.637    0.428992  26.829582   84.592300  ...
2010-01-06   22.850569  6.009    0.431736  26.610369   84.651871  ...
2010-01-07   22.612925  5.806    0.423275  26.481432   85.009232  ...
2010-01-08   22.768877  5.749    0.424189  26.442736   85.292099  ...
...                ...    ...         ...        ...         ...  ...
2026-09-28  509.220001  3.000  228.860001  96.470001  765.609985  ...
2026-09-29  508.959991  3.011  227.210007  95.139999  764.200012  ...
2026-09-30  512.900024  3.026  228.380005  95.050003  762.630005  ...
2026-10-01  512.799988  2.967  230.860001  95.610001  763.989990  ...
2026-10-02  517.530029  3.035  233.949997  96.230003  769.640015  ...

Price            Volume                                               \
Ticker              BAC     BZ=F         GLD         JPM        MSFT
Date
2010-01-04  180845200.0     97.0  16224100.0  35460500.0  38409100.0
2010-01-05  209521300.0     97.0  14213100.0  41208300.0  49749600.0
2010-01-06  205257900.0      7.0  24981900.0  27729000.0  58182400.0
2010-01-07  320868400.0      7.0  13609800.0  44864700.0  50559700.0
2010-01-08  220104700.0      7.0  15894600.0  33110100.0  51197400.0
...                 ...      ...         ...         ...         ...
2026-09-28   29170500.0  15803.0  14843400.0  10483700.0  19626900.0
2026-09-29   31666600.0  11974.0   8122800.0   7254900.0  21341800.0
2026-09-30   34023700.0  53689.0   7016200.0   9113300.0  27223300.0
2026-10-01   60049500.0  54607.0   6095900.0   8160000.0  19731900.0
2026-10-02   35067800.0  52249.0   9154900.0   6658200.0  17803300.0

Price
Ticker          NG=F         NVDA       SHEL          SPY         XOM
Date
2010-01-04   78858.0  800204000.0  1643003.0  118944600.0  27809100.0
2010-01-05   99492.0  728648000.0  1718458.0  111579900.0  30174700.0
2010-01-06  140611.0  649168000.0  3040554.0  116074400.0  35044700.0
2010-01-07  135113.0  547792000.0  1033089.0  131091100.0  27192100.0
2010-01-08  101153.0  478168000.0  1438017.0  126402800.0  24891800.0
...              ...          ...        ...          ...         ...
2026-09-28  212563.0  142344300.0  7700068.0   42694500.0  12809500.0
2026-09-29  188222.0  101494900.0  7477227.0   36910500.0   9160000.0
2026-09-30  147009.0  121732200.0  9918838.0   62110000.0  13100400.0
2026-10-01  153083.0   98591400.0  9736901.0   47708100.0  11703100.0
2026-10-02  178518.0  134914600.0  6577954.0   46306400.0  11287000.0

[4216 rows x 55 columns]

In [5]:
# We only keep the Close values and we check dates order
data = data["Close"].sort_index()
data.tail()

Ticker,AAPL,BAC,BZ=F,GLD,JPM,MSFT,NG=F,NVDA,SHEL,SPY,XOM
Date,,,,,,,,,,,
2026-09-28,338.399994,55.470001,105.279999,377.910004,336.589996,509.220001,3.000,228.860001,96.470001,765.609985,162.520004
2026-09-29,329.399994,54.959999,102.589996,382.890015,334.980011,508.959991,3.011,227.210007,95.139999,764.200012,161.350006
2026-09-30,333.019989,54.430000,103.529999,380.839996,330.829987,512.900024,3.026,228.380005,95.050003,762.630005,162.750000
2026-10-01,330.320007,53.730000,102.309998,382.760010,333.179993,512.799988,2.967,230.860001,95.610001,763.989990,163.820007
2026-10-02,333.690002,53.750000,102.250000,380.140015,332.380005,517.530029,3.035,233.949997,96.230003,769.640015,164.009995

In [6]:
# Renaming the columns

data.rename(columns={
    
    "SPY": "S&P 500",
    "AAPL": "Apple",
    "NVDA": "Nvidia",
    "MSFT": "Microsoft",
    "JPM": "JPMorgan",
    "BAC": "Bank of America",
    "SHEL": "Shell",
    "XOM": "Exxon Mobil",
    "GLD": "Gold",
    "BZ=F": "Oil",
    "NG=F": "Gas"
    
},inplace = True)

In [7]:
data.head()

Ticker,Apple,Bank of America,Oil,Gold,JPMorgan,Microsoft,Gas,Nvidia,Shell,S&P 500,Exxon Mobil
Date,,,,,,,,,,,
2010-01-04,6.400960,11.977122,80.120003,109.800003,28.152376,22.984241,5.884,0.422817,26.799503,84.369003,37.136810
2010-01-05,6.412027,12.366440,80.589996,109.699997,28.697685,22.991663,5.637,0.428992,26.829582,84.592300,37.281815
2010-01-06,6.310033,12.511472,81.889999,111.510002,28.855364,22.850569,6.009,0.431736,26.610369,84.651871,37.604038
2010-01-07,6.298368,12.923692,81.510002,110.820000,29.426964,22.612925,5.806,0.423275,26.481432,85.009232,37.485893
2010-01-08,6.340244,12.809187,81.370003,111.370003,29.354692,22.768877,5.749,0.424189,26.442736,85.292099,37.335514

In [8]:
# Removing NaN values

data.dropna(inplace=True)
data.isna().sum()

Ticker
Apple              0
Bank of America    0
Oil                0
Gold               0
JPMorgan           0
Microsoft          0
Gas                0
Nvidia             0
Shell              0
S&P 500            0
Exxon Mobil        0
dtype: int64

In [9]:
# Changing columns order

column = ["S&P 500", "Nvidia", "Apple", "Microsoft", "JPMorgan", "Bank of America", "Exxon Mobil", "Shell", "Gold", "Oil", "Gas" ]
data = data[column]

In [10]:
data

Ticker,S&P 500,Nvidia,Apple,Microsoft,JPMorgan,Bank of America,Exxon Mobil,Shell,Gold,Oil,Gas
Date,,,,,,,,,,,
2010-01-04,84.369003,0.422817,6.400960,22.984241,28.152376,11.977122,37.136810,26.799503,109.800003,80.120003,5.884
2010-01-05,84.592300,0.428992,6.412027,22.991663,28.697685,12.366440,37.281815,26.829582,109.699997,80.589996,5.637
2010-01-06,84.651871,0.431736,6.310033,22.850569,28.855364,12.511472,37.604038,26.610369,111.510002,81.889999,6.009
2010-01-07,85.009232,0.423275,6.298368,22.612925,29.426964,12.923692,37.485893,26.481432,110.820000,81.510002,5.806
2010-01-08,85.292099,0.424189,6.340244,22.768877,29.354692,12.809187,37.335514,26.442736,111.370003,81.370003,5.749
...,...,...,...,...,...,...,...,...,...,...,...
2026-09-28,765.609985,228.860001,338.399994,509.220001,336.589996,55.470001,162.520004,96.470001,377.910004,105.279999,3.000
2026-09-29,764.200012,227.210007,329.399994,508.959991,334.980011,54.959999,161.350006,95.139999,382.890015,102.589996,3.011
2026-09-30,762.630005,228.380005,333.019989,512.900024,330.829987,54.430000,162.750000,95.050003,380.839996,103.529999,3.026
2026-10-01,763.989990,230.860001,330.320007,512.799988,333.179993,53.730000,163.820007,95.610001,382.760010,102.309998,2.967
2026-10-02,769.640015,233.949997,333.690002,517.530029,332.380005,53.750000,164.009995,96.230003,380.140015,102.250000,3.035

In [11]:
# nan il faut que je fasse des rendements logarithmiques pour derriè exprimer le drift


returns = data.pct_change()
returns.dropna(inplace=True)
returns

Ticker,S&P 500,Nvidia,Apple,Microsoft,JPMorgan,Bank of America,Exxon Mobil,Shell,Gold,Oil,Gas
Date,,,,,,,,,,,
2010-01-05,0.002647,0.014603,0.001729,0.000323,0.019370,0.032505,0.003905,0.001122,-0.000911,0.005866,-0.041978
2010-01-06,0.000704,0.006397,-0.015907,-0.006137,0.005494,0.011728,0.008643,-0.008171,0.016500,0.016131,0.065993
2010-01-07,0.004222,-0.019597,-0.001849,-0.010400,0.019809,0.032947,-0.003142,-0.004845,-0.006188,-0.004640,-0.033783
2010-01-08,0.003327,0.002161,0.006649,0.006897,-0.002456,-0.008860,-0.004012,-0.001461,0.004963,-0.001718,-0.009817
2010-01-11,0.001396,-0.014016,-0.008821,-0.012720,-0.003357,0.008939,0.011220,0.015605,0.013289,-0.004916,-0.051313
...,...,...,...,...,...,...,...,...,...,...,...
2026-09-28,-0.007441,0.016839,-0.007828,-0.013465,-0.018860,-0.021693,0.012018,0.007204,-0.039399,0.009202,-0.061327
2026-09-29,-0.001842,-0.007210,-0.026596,-0.000511,-0.004783,-0.009194,-0.007199,-0.013787,0.013178,-0.025551,0.003667
2026-09-30,-0.002054,0.005149,0.010990,0.007741,-0.012389,-0.009643,0.008677,-0.000946,-0.005354,0.009163,0.004982
2026-10-01,0.001783,0.010859,-0.008108,-0.000195,0.007103,-0.012861,0.006575,0.005892,0.005042,-0.011784,-0.019498
2026-10-02,0.007395,0.013385,0.010202,0.009224,-0.002401,0.000372,0.001160,0.006485,-0.006845,-0.000586,0.022919

In [12]:
# Defining the portfolio weight

weight_Nvidia = 0.13
weight_Apple = 0.15
weight_Microsoft = 0.13
weight_JPMorgan = 0.10
weight_Bank_of_America = 0.10
weight_Exxon_Mobil = 0.04
weight_Shell = 0.04
weight_Gold = 0.1
weight_Gas = 0.04


weight_SP500_put = 0.07
weight_Oil_straddle = 0.1

s = weight_Nvidia + weight_Apple + weight_Microsoft + weight_JPMorgan + weight_Bank_of_America  + weight_Exxon_Mobil + weight_Shell + weight_Gold + weight_Oil_straddle + weight_Gas + weight_SP500_put
print(s)

1.0