In [1]:
import numpy as np
import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt
from datetime import date
import statsmodels.api as sm

In [2]:
# Assets for the portfolio

tickers = [
    "SPY",   # S&P 500 ETF
    "AAPL",  # Apple
    "NVDA",  # Nvidia
    "MSFT",  # Microsoft
    "JPM",   # JPMorgan Chase
    "BAC",   # Bank of America
    "SHEL",  # Shell
    "XOM",   # Exxon Mobil
    "GLD",   # SPDR Gold Shares
    "BZ=F",  # Brent crude oil futures
    "NG=F"   # Natural gas (Henry Hub) futures
]


# Time period
START_DATE = "2010-01-01"
END_DATE = date.today().strftime("%Y-%m-%d")

In [3]:
# Getting data from Yahoo Finance

data = yf.download(
    tickers,
    start=START_DATE,
    end=END_DATE,
    interval="1d",
    auto_adjust=True,
    progress=False
)

In [4]:
data

Price            Close                                                 \
Ticker            AAPL        BAC        BZ=F         GLD         JPM
Date
2010-01-04    6.400960  11.977124   80.120003  109.800003   28.152388
2010-01-05    6.412026  12.366440   80.589996  109.699997   28.697687
2010-01-06    6.310036  12.511472   81.889999  111.510002   28.855364
2010-01-07    6.298369  12.923686   81.510002  110.820000   29.426966
2010-01-08    6.340243  12.809184   81.370003  111.370003   29.354685
...                ...        ...         ...         ...         ...
2026-09-28  338.399994  55.470001  105.279999  377.910004  336.589996
2026-09-29  329.399994  54.959999  102.589996  382.890015  334.980011
2026-09-30  333.019989  54.430000  103.529999  380.839996  330.829987
2026-10-01  330.320007  53.730000  102.309998  382.760010  333.179993
2026-10-02  333.690002  53.750000  102.250000  380.140015  332.380005

Price                                                             ...  \
Ticker            MSFT   NG=F        NVDA       SHEL         SPY  ...
Date                                                              ...
2010-01-04   22.984238  5.884    0.422817  26.799492   84.368973  ...
2010-01-05   22.991665  5.637    0.428992  26.829588   84.592331  ...
2010-01-06   22.850565  6.009    0.431736  26.610373   84.651863  ...
2010-01-07   22.612932  5.806    0.423275  26.481426   85.009201  ...
2010-01-08   22.768879  5.749    0.424189  26.442739   85.292099  ...
...                ...    ...         ...        ...         ...  ...
2026-09-28  509.220001  3.000  228.860001  96.470001  765.609985  ...
2026-09-29  508.959991  3.011  227.210007  95.139999  764.200012  ...
2026-09-30  512.900024  3.026  228.380005  95.050003  762.630005  ...
2026-10-01  512.799988  2.967  230.860001  95.610001  763.989990  ...
2026-10-02  517.530029  3.035  233.949997  96.230003  769.640015  ...

Price            Volume                                               \
Ticker              BAC     BZ=F         GLD         JPM        MSFT
Date
2010-01-04  180845200.0     97.0  16224100.0  35460500.0  38409100.0
2010-01-05  209521300.0     97.0  14213100.0  41208300.0  49749600.0
2010-01-06  205257900.0      7.0  24981900.0  27729000.0  58182400.0
2010-01-07  320868400.0      7.0  13609800.0  44864700.0  50559700.0
2010-01-08  220104700.0      7.0  15894600.0  33110100.0  51197400.0
...                 ...      ...         ...         ...         ...
2026-09-28   29170500.0  15803.0  14843400.0  10483700.0  19626900.0
2026-09-29   31666600.0  11974.0   8122800.0   7254900.0  21341800.0
2026-09-30   34023700.0  53689.0   7016200.0   9113300.0  27223300.0
2026-10-01   60049500.0  54607.0   6095900.0   8160000.0  19731900.0
2026-10-02   35067800.0  52249.0   9154900.0   6658200.0  17803300.0

Price
Ticker          NG=F         NVDA       SHEL          SPY         XOM
Date
2010-01-04   78858.0  800204000.0  1643003.0  118944600.0  27809100.0
2010-01-05   99492.0  728648000.0  1718458.0  111579900.0  30174700.0
2010-01-06  140611.0  649168000.0  3040554.0  116074400.0  35044700.0
2010-01-07  135113.0  547792000.0  1033089.0  131091100.0  27192100.0
2010-01-08  101153.0  478168000.0  1438017.0  126402800.0  24891800.0
...              ...          ...        ...          ...         ...
2026-09-28  212563.0  142344300.0  7700068.0   42694500.0  12809500.0
2026-09-29  188222.0  101494900.0  7477227.0   36910500.0   9160000.0
2026-09-30  147009.0  121732200.0  9918838.0   62110000.0  13100400.0
2026-10-01  153083.0   98591400.0  9736901.0   47708100.0  11703100.0
2026-10-02  178518.0  134914600.0  6577954.0   46306400.0  11287000.0

[4216 rows x 55 columns]

In [5]:
# We only keep the Close values and we check dates order
data = data["Close"].sort_index()
data.tail()

Ticker,AAPL,BAC,BZ=F,GLD,JPM,MSFT,NG=F,NVDA,SHEL,SPY,XOM
Date,,,,,,,,,,,
2026-09-28,338.399994,55.470001,105.279999,377.910004,336.589996,509.220001,3.000,228.860001,96.470001,765.609985,162.520004
2026-09-29,329.399994,54.959999,102.589996,382.890015,334.980011,508.959991,3.011,227.210007,95.139999,764.200012,161.350006
2026-09-30,333.019989,54.430000,103.529999,380.839996,330.829987,512.900024,3.026,228.380005,95.050003,762.630005,162.750000
2026-10-01,330.320007,53.730000,102.309998,382.760010,333.179993,512.799988,2.967,230.860001,95.610001,763.989990,163.820007
2026-10-02,333.690002,53.750000,102.250000,380.140015,332.380005,517.530029,3.035,233.949997,96.230003,769.640015,164.009995

In [6]:
# Renaming the columns

data.rename(columns={
    
    "SPY": "S&P 500",
    "AAPL": "Apple",
    "NVDA": "Nvidia",
    "MSFT": "Microsoft",
    "JPM": "JPMorgan",
    "BAC": "Bank of America",
    "SHEL": "Shell",
    "XOM": "Exxon Mobil",
    "GLD": "Gold",
    "BZ=F": "Oil",
    "NG=F": "Gas"
    
},inplace = True)

In [7]:
data.head()

Ticker,Apple,Bank of America,Oil,Gold,JPMorgan,Microsoft,Gas,Nvidia,Shell,S&P 500,Exxon Mobil
Date,,,,,,,,,,,
2010-01-04,6.400960,11.977124,80.120003,109.800003,28.152388,22.984238,5.884,0.422817,26.799492,84.368973,37.136818
2010-01-05,6.412026,12.366440,80.589996,109.699997,28.697687,22.991665,5.637,0.428992,26.829588,84.592331,37.281811
2010-01-06,6.310036,12.511472,81.889999,111.510002,28.855364,22.850565,6.009,0.431736,26.610373,84.651863,37.604027
2010-01-07,6.298369,12.923686,81.510002,110.820000,29.426966,22.612932,5.806,0.423275,26.481426,85.009201,37.485901
2010-01-08,6.340243,12.809184,81.370003,111.370003,29.354685,22.768879,5.749,0.424189,26.442739,85.292099,37.335506

In [8]:
# Removing NaN values

data.dropna(inplace=True)
data.isna().sum()

Ticker
Apple              0
Bank of America    0
Oil                0
Gold               0
JPMorgan           0
Microsoft          0
Gas                0
Nvidia             0
Shell              0
S&P 500            0
Exxon Mobil        0
dtype: int64

In [9]:
# Changing columns order

column = ["S&P 500", "Nvidia", "Apple", "Microsoft", "JPMorgan", "Bank of America", "Exxon Mobil", "Shell", "Gold", "Oil", "Gas" ]
data = data[column]

In [10]:
data

Ticker,S&P 500,Nvidia,Apple,Microsoft,JPMorgan,Bank of America,Exxon Mobil,Shell,Gold,Oil,Gas
Date,,,,,,,,,,,
2010-01-04,84.368973,0.422817,6.400960,22.984238,28.152388,11.977124,37.136818,26.799492,109.800003,80.120003,5.884
2010-01-05,84.592331,0.428992,6.412026,22.991665,28.697687,12.366440,37.281811,26.829588,109.699997,80.589996,5.637
2010-01-06,84.651863,0.431736,6.310036,22.850565,28.855364,12.511472,37.604027,26.610373,111.510002,81.889999,6.009
2010-01-07,85.009201,0.423275,6.298369,22.612932,29.426966,12.923686,37.485901,26.481426,110.820000,81.510002,5.806
2010-01-08,85.292099,0.424189,6.340243,22.768879,29.354685,12.809184,37.335506,26.442739,111.370003,81.370003,5.749
...,...,...,...,...,...,...,...,...,...,...,...
2026-09-28,765.609985,228.860001,338.399994,509.220001,336.589996,55.470001,162.520004,96.470001,377.910004,105.279999,3.000
2026-09-29,764.200012,227.210007,329.399994,508.959991,334.980011,54.959999,161.350006,95.139999,382.890015,102.589996,3.011
2026-09-30,762.630005,228.380005,333.019989,512.900024,330.829987,54.430000,162.750000,95.050003,380.839996,103.529999,3.026
2026-10-01,763.989990,230.860001,330.320007,512.799988,333.179993,53.730000,163.820007,95.610001,382.760010,102.309998,2.967
2026-10-02,769.640015,233.949997,333.690002,517.530029,332.380005,53.750000,164.009995,96.230003,380.140015,102.250000,3.035

In [11]:
# Calculate asset returns

def returns(column):
    return np.log(column/column.shift(1))

df_returns = data.apply(returns)
df_returns.dropna(inplace=True)
df_returns

Ticker,S&P 500,Nvidia,Apple,Microsoft,JPMorgan,Bank of America,Exxon Mobil,Shell,Gold,Oil,Gas
Date,,,,,,,,,,,
2010-01-05,0.002644,0.014497,0.001727,0.000323,0.019184,0.031988,0.003897,0.001122,-0.000911,0.005849,-0.042885
2010-01-06,0.000704,0.006376,-0.016034,-0.006156,0.005479,0.011660,0.008606,-0.008204,0.016365,0.016002,0.063906
2010-01-07,0.004212,-0.019792,-0.001851,-0.010454,0.019616,0.032416,-0.003146,-0.004857,-0.006207,-0.004651,-0.034366
2010-01-08,0.003322,0.002159,0.006626,0.006873,-0.002459,-0.008899,-0.004020,-0.001462,0.004951,-0.001719,-0.009866
2010-01-11,0.001396,-0.014115,-0.008860,-0.012802,-0.003363,0.008899,0.011158,0.015484,0.013201,-0.004928,-0.052677
...,...,...,...,...,...,...,...,...,...,...,...
2026-09-28,-0.007469,0.016699,-0.007859,-0.013556,-0.019040,-0.021932,0.011947,0.007178,-0.040196,0.009160,-0.063288
2026-09-29,-0.001843,-0.007236,-0.026956,-0.000511,-0.004795,-0.009237,-0.007225,-0.013883,0.013092,-0.025883,0.003660
2026-09-30,-0.002057,0.005136,0.010930,0.007712,-0.012466,-0.009690,0.008639,-0.000946,-0.005368,0.009121,0.004969
2026-10-01,0.001782,0.010801,-0.008141,-0.000195,0.007078,-0.012944,0.006553,0.005874,0.005029,-0.011854,-0.019690
2026-10-02,0.007368,0.013296,0.010151,0.009182,-0.002404,0.000372,0.001159,0.006464,-0.006869,-0.000587,0.022660

In [12]:
# Parameters values
mu = df_returns.mean()
mu

Ticker
S&P 500            0.000529
Nvidia             0.001512
Apple              0.000946
Microsoft          0.000745
JPMorgan           0.000591
Bank of America    0.000359
Exxon Mobil        0.000356
Shell              0.000306
Gold               0.000297
Oil                0.000058
Gas               -0.000158
dtype: float64

In [13]:
mu = df_returns.mean().values   # daily average return for each asset
mu

array([ 5.29134318e-04,  1.51170953e-03,  9.46329452e-04,  7.45394660e-04,
        5.90868056e-04,  3.59345417e-04,  3.55509453e-04,  3.05973735e-04,
        2.97242481e-04,  5.83760770e-05, -1.58455079e-04])

In [14]:
# std
sigma = df_returns.cov()  # daily covariance matrix
sigma

Ticker,S&P 500,Nvidia,Apple,Microsoft,JPMorgan,Bank of America,Exxon Mobil,Shell,Gold,Oil,Gas
Ticker,,,,,,,,,,,
S&P 500,0.000117,0.000196,0.000130,0.000129,0.000137,0.000157,0.000095,0.000106,0.000008,0.000065,0.000024
Nvidia,0.000196,0.000810,0.000237,0.000256,0.000181,0.000214,0.000101,0.000130,0.000012,0.000085,0.000043
Apple,0.000130,0.000237,0.000316,0.000162,0.000120,0.000143,0.000083,0.000093,0.000009,0.000062,0.000015
Microsoft,0.000129,0.000256,0.000162,0.000271,0.000122,0.000139,0.000075,0.000094,0.000006,0.000059,0.000040
JPMorgan,0.000137,0.000181,0.000120,0.000122,0.000299,0.000306,0.000142,0.000156,-0.000007,0.000095,0.000019
Bank of America,0.000157,0.000214,0.000143,0.000139,0.000306,0.000434,0.000163,0.000172,-0.000013,0.000110,0.000021
Exxon Mobil,0.000095,0.000101,0.000083,0.000075,0.000142,0.000163,0.000251,0.000208,0.000009,0.000194,0.000059
Shell,0.000106,0.000130,0.000093,0.000094,0.000156,0.000172,0.000208,0.000307,0.000022,0.000212,0.000052
Gold,0.000008,0.000012,0.000009,0.000006,-0.000007,-0.000013,0.000009,0.000022,0.000113,0.000022,0.000009
Oil,0.000065,0.000085,0.000062,0.000059,0.000095,0.000110,0.000194,0.000212,0.000022,0.000550,0.000080
Gas,0.000024,0.000043,0.000015,0.000040,0.000019,0.000021,0.000059,0.000052,0.000009,0.000080,0.001471

In [15]:
sigma = df_returns.cov().values
sigma # array matrix

array([[ 1.17066812e-04,  1.96242999e-04,  1.30236819e-04,
         1.29009792e-04,  1.36678171e-04,  1.57454966e-04,
         9.46027246e-05,  1.05565940e-04,  8.16083562e-06,
         6.54274775e-05,  2.38189837e-05],
       [ 1.96242999e-04,  8.10197557e-04,  2.37353769e-04,
         2.56141527e-04,  1.81019131e-04,  2.13572377e-04,
         1.01131673e-04,  1.29849020e-04,  1.16134566e-05,
         8.49157653e-05,  4.33114916e-05],
       [ 1.30236819e-04,  2.37353769e-04,  3.16337598e-04,
         1.61931596e-04,  1.19950788e-04,  1.42902726e-04,
         8.27740430e-05,  9.28090841e-05,  9.44377716e-06,
         6.21277229e-05,  1.48463156e-05],
       [ 1.29009792e-04,  2.56141527e-04,  1.61931596e-04,
         2.70847840e-04,  1.21944667e-04,  1.38904809e-04,
         7.49626413e-05,  9.38778399e-05,  6.21836474e-06,
         5.92008525e-05,  3.96887987e-05],
       [ 1.36678171e-04,  1.81019131e-04,  1.19950788e-04,
         1.21944667e-04,  2.99339801e-04,  3.05955664e-04,
         1.41756105e-04,  1.56004135e-04, -6.79508944e-06,
         9.53250162e-05,  1.88031252e-05],
       [ 1.57454966e-04,  2.13572377e-04,  1.42902726e-04,
         1.38904809e-04,  3.05955664e-04,  4.34304769e-04,
         1.62988526e-04,  1.72453513e-04, -1.25640223e-05,
         1.10222406e-04,  2.10605455e-05],
       [ 9.46027246e-05,  1.01131673e-04,  8.27740430e-05,
         7.49626413e-05,  1.41756105e-04,  1.62988526e-04,
         2.50874331e-04,  2.07874790e-04,  8.66066157e-06,
         1.94270410e-04,  5.91819993e-05],
       [ 1.05565940e-04,  1.29849020e-04,  9.28090841e-05,
         9.38778399e-05,  1.56004135e-04,  1.72453513e-04,
         2.07874790e-04,  3.07231312e-04,  2.24421209e-05,
         2.11984004e-04,  5.17842988e-05],
       [ 8.16083562e-06,  1.16134566e-05,  9.44377716e-06,
         6.21836474e-06, -6.79508944e-06, -1.25640223e-05,
         8.66066157e-06,  2.24421209e-05,  1.13278684e-04,
         2.17334873e-05,  9.44423251e-06],
       [ 6.54274775e-05,  8.49157653e-05,  6.21277229e-05,
         5.92008525e-05,  9.53250162e-05,  1.10222406e-04,
         1.94270410e-04,  2.11984004e-04,  2.17334873e-05,
         5.50469577e-04,  8.00781940e-05],
       [ 2.38189837e-05,  4.33114916e-05,  1.48463156e-05,
         3.96887987e-05,  1.88031252e-05,  2.10605455e-05,
         5.91819993e-05,  5.17842988e-05,  9.44423251e-06,
         8.00781940e-05,  1.47117964e-03]])

In [17]:
MC = 1000 # 100 000 simulations
rng = np.random.default_rng()

simulated_returns = rng.multivariate_normal(mean=mu,cov=sigma,size=MC)  # matrix MC rows and N = number of assets columns
# for each asset, we have 100,000 return scenarios
simulated_returns

array([[ 0.01046242,  0.01034288,  0.00819131, ...,  0.01226301,
         0.01182483, -0.02603811],
       [-0.00990874, -0.0381376 , -0.01119666, ..., -0.00669275,
        -0.00137547,  0.00962298],
       [-0.00260632,  0.00443072,  0.02012676, ...,  0.0139483 ,
         0.00600782,  0.00472126],
       ...,
       [ 0.01191465,  0.01334121,  0.0078965 , ..., -0.01521701,
         0.04127128,  0.05377417],
       [ 0.00768455,  0.00988576,  0.00733314, ..., -0.00459337,
         0.01528096,  0.02773072],
       [ 0.0180121 ,  0.06160428,  0.02316686, ..., -0.01058179,
         0.00491445,  0.07106749]], shape=(1000, 11))

In [12]:
# Defining the portfolio weight

weight_Nvidia = 0.13
weight_Apple = 0.15
weight_Microsoft = 0.13
weight_JPMorgan = 0.10
weight_Bank_of_America = 0.10
weight_Exxon_Mobil = 0.04
weight_Shell = 0.04
weight_Gold = 0.1
weight_Gas = 0.04


weight_SP500_put = 0.07
weight_Oil_straddle = 0.1

s = weight_Nvidia + weight_Apple + weight_Microsoft + weight_JPMorgan + weight_Bank_of_America  + weight_Exxon_Mobil + weight_Shell + weight_Gold + weight_Oil_straddle + weight_Gas + weight_SP500_put
print(s)

1.0